/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'adventure' : IDL.Null,
  'puzzle' : IDL.Null,
  'racing' : IDL.Null,
  'fantasy' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
  'coverPath' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getStoriesByCategory' : IDL.Func([Category], [IDL.Vec(Story)], ['query']),
  'getStoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'adventure' : IDL.Null,
    'puzzle' : IDL.Null,
    'racing' : IDL.Null,
    'fantasy' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
    'coverPath' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getStoriesByCategory' : IDL.Func([Category], [IDL.Vec(Story)], ['query']),
    'getStoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };